### ISSUE TITLE
Unable to get fully installed and setup 

### ISSUE THREAD

**Issue by JohnnyZ** [JustinAzoff/asnlookup#1]
Hey Justin,

Thanks for taking the time to develop this. I need to use this for a project and I cannot figure out what is going on. I have setup the asnlookup package (python setup.py install) as well as any requirements with pip. Am I supposed to be setting anything else up? Thank you in advance.

`echo -e "8.8.8.8" | asnlookup
DEBUG:asnlookup.data_manager:file_age_in_hours: filename=asn.db does not exist
DEBUG:asnlookup.data_manager:download_and_convert working_dir=/tmp/tmpxbpJQw
DEBUG:asnlookup.data_manager:Executing cmd=['pyasn_util_download.py', '--latestv4']
usage: /usr/local/bin/pyasn_util_download.py [--dates-from-file FILEWITHDATES] | [--latest]

       The script downloads MRT dump files from ROUTEVIEWS for the dates specified. It requires wget.
Traceback (most recent call last):
  File "/usr/local/bin/asnlookup", line 11, in <module>
    load_entry_point('asnlookup==0.0.3', 'console_scripts', 'asnlookup')()
  File "build/bdist.linux-x86_64/egg/asnlookup/main.py", line 9, in main
  File "build/bdist.linux-x86_64/egg/asnlookup/backend.py", line 38, in __init__
  File "build/bdist.linux-x86_64/egg/asnlookup/data_manager.py", line 113, in update_asndb
  File "build/bdist.linux-x86_64/egg/asnlookup/data_manager.py", line 54, in maybe_update
  File "build/bdist.linux-x86_64/egg/asnlookup/data_manager.py", line 91, in download_and_convert
  File "build/bdist.linux-x86_64/egg/asnlookup/data_manager.py", line 72, in get_single_file
asnlookup.data_manager.DataManagerError: ('More than one file found: files=%s', [])
`

**Comment by JohnnyZ** [comment]
I have updated my pyasn as there seems to have been a bug fix for my issue and everything seems to be working appropriately. Your docker may also be configured to use an older version(MRT RIB log importer 1.5.0b7) which does not appear to be working.

Thank you again for writing this.
